name: fit_25
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2 # Cập nhật phiên bản http
  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.2.2
  provider: ^6.1.2
  shelf: ^1.2.0
  shelf_router: ^1.0.0
  google_generative_ai: ^0.4.6
  flutter_markdown: ^0.7.4+1

assets:
  - - assets/Images/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  

