name: fit_25
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.2.2
  provider: ^6.1.2
  shelf: ^1.2.1
  shelf_router: ^1.0.0
  google_generative_ai: ^0.4.6
  flutter_markdown: 0.7.4+2
  flutter_gemini: ^2.0.5
  image_picker: ^1.1.2
  dash_chat_2: ^0.0.21
  geolocator: ^13.0.2
  charts_flutter: ^0.12.0
  fl_chart: ^0.69.2
  url_launcher: ^6.3.1
  pedometer: ^4.0.0  
  permission_handler: ^11.3.1
  heart_bpm: ^2.0.0+0


dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Images/User.jpg
  

